### ISSUE TITLE
Using Variables and Backreferences in Replace

### ISSUE THREAD

**Issue by PilHliP211** [knom/vsts-regex-tasks#23]
I'm trying to replace all strings in RC files that match 0[.,]0[.,]0 with major.minor.build or major,minor,build (depending on the first capture group's contents)

```
- task: RegexReplace@3
  displayName: 'Version Cpp'
  inputs:
    InputSearchPattern: '**\*.rc'
    FindRegex: '0([.,])0[.,]0'
    ReplaceRegex: '$(major)$1$(minor)$1$(build)'
    UseUTF8: true
```
When I run this, it properly populates the major, minor and build variables with their correct value, but the backreference to the first capture group is not being resolved - it is using a literal "$1"

How can I use both Build Variables AND backreferences in the same replace pattern?
Instead of using $1, I have also tried \1 and \\1, all of which printed the literal string after evaluation.
